// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryCommandExecutionApprovalDecision } from "./FactoryCommandExecutionApprovalDecision";
import type { FactoryExecPolicyAmendment } from "./FactoryExecPolicyAmendment";
import type { FactoryNetworkPolicyAmendment } from "./FactoryNetworkPolicyAmendment";
import type { ItemId } from "./ItemId";
import type { ThreadId } from "./ThreadId";
import type { TurnId } from "./TurnId";
import type { JsonValue } from "./serde_json/JsonValue";

export type FactoryCommandExecutionRequestApprovalParams = { threadId: ThreadId, turnId: TurnId, itemId: ItemId, startedAtMs: number, approvalId?: string, environmentId: string | null, reason?: string, networkApprovalContext?: JsonValue, command?: string, cwd?: string, commandActions?: Array<JsonValue>, additionalPermissions?: JsonValue, proposedExecpolicyAmendment?: FactoryExecPolicyAmendment, proposedNetworkPolicyAmendments?: Array<FactoryNetworkPolicyAmendment>, availableDecisions?: Array<FactoryCommandExecutionApprovalDecision>, };
