// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryAttestationGenerateParams } from "./FactoryAttestationGenerateParams";
import type { FactoryChatgptAuthTokensRefreshParams } from "./FactoryChatgptAuthTokensRefreshParams";
import type { FactoryCommandExecutionRequestApprovalParams } from "./FactoryCommandExecutionRequestApprovalParams";
import type { FactoryCurrentTimeReadParams } from "./FactoryCurrentTimeReadParams";
import type { FactoryDynamicToolCallParams } from "./FactoryDynamicToolCallParams";
import type { FactoryFileChangeRequestApprovalParams } from "./FactoryFileChangeRequestApprovalParams";
import type { FactoryMcpServerElicitationRequestParams } from "./FactoryMcpServerElicitationRequestParams";
import type { FactoryPermissionsRequestApprovalParams } from "./FactoryPermissionsRequestApprovalParams";
import type { FactoryRpcRequestId } from "./FactoryRpcRequestId";
import type { FactoryToolRequestUserInputParams } from "./FactoryToolRequestUserInputParams";

/**
 * A typed request initiated by Codex app-server and delivered to the Factory
 * host. The request id must be echoed unchanged in the matching response.
 */
export type FactoryServerRequest = { "method": "item/commandExecution/requestApproval", id: FactoryRpcRequestId, params: FactoryCommandExecutionRequestApprovalParams, } | { "method": "item/fileChange/requestApproval", id: FactoryRpcRequestId, params: FactoryFileChangeRequestApprovalParams, } | { "method": "item/tool/requestUserInput", id: FactoryRpcRequestId, params: FactoryToolRequestUserInputParams, } | { "method": "mcpServer/elicitation/request", id: FactoryRpcRequestId, params: FactoryMcpServerElicitationRequestParams, } | { "method": "item/permissions/requestApproval", id: FactoryRpcRequestId, params: FactoryPermissionsRequestApprovalParams, } | { "method": "item/tool/call", id: FactoryRpcRequestId, params: FactoryDynamicToolCallParams, } | { "method": "account/chatgptAuthTokens/refresh", id: FactoryRpcRequestId, params: FactoryChatgptAuthTokensRefreshParams, } | { "method": "attestation/generate", id: FactoryRpcRequestId, params: FactoryAttestationGenerateParams, } | { "method": "currentTime/read", id: FactoryRpcRequestId, params: FactoryCurrentTimeReadParams, };
