// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryErrorEnvelope } from "./FactoryErrorEnvelope";
import type { FactoryResponseEnvelope } from "./FactoryResponseEnvelope";

export type FactoryResponseOutcome = { "type": "success", response: FactoryResponseEnvelope, } | { "type": "error", error: FactoryErrorEnvelope, };
