// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttemptId } from "./AttemptId";
import type { FactoryRequestId } from "./FactoryRequestId";
import type { ItemId } from "./ItemId";
import type { JobId } from "./JobId";
import type { OperationId } from "./OperationId";
import type { TaskRunExternalId } from "./TaskRunExternalId";
import type { ThreadId } from "./ThreadId";
import type { TurnId } from "./TurnId";
import type { WorkflowRunId } from "./WorkflowRunId";

export type FactoryCorrelation = { jobId: JobId, operationId: OperationId, attemptId: AttemptId, workflowRunId?: WorkflowRunId, taskRunExternalId?: TaskRunExternalId, requestId: FactoryRequestId, threadId?: ThreadId, turnId?: TurnId, itemId?: ItemId, };
