// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON-RPC request identifier used by the Codex app-server wire protocol.
 *
 * App-server accepts either a string or a signed integer and requires the
 * response to echo the same representation. Keeping this separate from
 * [`FactoryRequestId`] prevents a numeric upstream request id from being
 * coerced into a string at the Factory boundary.
 */
export type FactoryRpcRequestId = string | number;
