// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryRawServerRequest } from "./FactoryRawServerRequest";
import type { FactoryServerRequest } from "./FactoryServerRequest";
import type { FactoryUnknownServerRequest } from "./FactoryUnknownServerRequest";

export type FactoryDecodedServerRequest = { "kind": "known", request: FactoryServerRequest, raw: FactoryRawServerRequest, } | { "kind": "unknown", request: FactoryUnknownServerRequest, };
