// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryPermissionGrantScope } from "./FactoryPermissionGrantScope";
import type { JsonValue } from "./serde_json/JsonValue";

export type FactoryPermissionsRequestApprovalResponse = { permissions: JsonValue, scope: FactoryPermissionGrantScope, strictAutoReview?: boolean, };
