// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryPlanStepStatus } from "./FactoryPlanStepStatus";

export type FactoryPlanStep = { step: string, status: FactoryPlanStepStatus, };
