// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryServerRequestIdentity } from "./FactoryServerRequestIdentity";

export type FactoryServerPayloadDecodeError = { "kind": "invalidKnownRequest", identity: FactoryServerRequestIdentity, message: string, } | { "kind": "invalidKnownResponse", identity: FactoryServerRequestIdentity, message: string, };
