// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryCorrelation } from "./FactoryCorrelation";
import type { FactoryDecodedServerRequest } from "./FactoryDecodedServerRequest";
import type { FactoryDecodedServerResponse } from "./FactoryDecodedServerResponse";
import type { FactoryErrorEnvelope } from "./FactoryErrorEnvelope";
import type { FactoryEvent } from "./FactoryEvent";
import type { FactoryJsonlMessage } from "./FactoryJsonlMessage";
import type { FactoryKnownServerRequestMethod } from "./FactoryKnownServerRequestMethod";
import type { FactoryMethodNotSupportedResolution } from "./FactoryMethodNotSupportedResolution";
import type { FactoryNotificationEnvelope } from "./FactoryNotificationEnvelope";
import type { FactoryPendingRequest } from "./FactoryPendingRequest";
import type { FactoryRawServerRequest } from "./FactoryRawServerRequest";
import type { FactoryRawServerResponse } from "./FactoryRawServerResponse";
import type { FactoryRequestEnvelope } from "./FactoryRequestEnvelope";
import type { FactoryResponseEnvelope } from "./FactoryResponseEnvelope";
import type { FactoryResponseOutcome } from "./FactoryResponseOutcome";
import type { FactoryServerErrorResponse } from "./FactoryServerErrorResponse";
import type { FactoryServerPayloadDecodeError } from "./FactoryServerPayloadDecodeError";
import type { FactoryServerRequest } from "./FactoryServerRequest";
import type { FactoryServerRequestIdentity } from "./FactoryServerRequestIdentity";
import type { FactoryServerRequestMethod } from "./FactoryServerRequestMethod";
import type { FactoryServerResponse } from "./FactoryServerResponse";
import type { FactoryServerResponsePairingError } from "./FactoryServerResponsePairingError";
import type { FactoryUnknownServerRequest } from "./FactoryUnknownServerRequest";
import type { FactoryUnknownServerResponse } from "./FactoryUnknownServerResponse";
import type { ProtocolManifest } from "./ProtocolManifest";
import type { ProtocolRange } from "./ProtocolRange";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * Export root used to generate the checked-in JSON Schema and TypeScript.
 */
export type FactoryProtocolSchema = { jsonlMessage: FactoryJsonlMessage, request: FactoryRequestEnvelope, response: FactoryResponseEnvelope, pendingRequest: FactoryPendingRequest, responseOutcome: FactoryResponseOutcome, notification: FactoryNotificationEnvelope, error: FactoryErrorEnvelope, event: FactoryEvent, serverRequest: FactoryServerRequest, serverResponse: FactoryServerResponse, rawServerRequest: FactoryRawServerRequest, decodedServerRequest: FactoryDecodedServerRequest, unknownServerRequest: FactoryUnknownServerRequest, rawServerResponse: FactoryRawServerResponse, decodedServerResponse: FactoryDecodedServerResponse, unknownServerResponse: FactoryUnknownServerResponse, serverErrorResponse: FactoryServerErrorResponse, methodNotSupportedResolution: FactoryMethodNotSupportedResolution, serverRequestIdentity: FactoryServerRequestIdentity, serverRequestMethod: FactoryServerRequestMethod, knownServerRequestMethod: FactoryKnownServerRequestMethod, serverResponsePairingError: FactoryServerResponsePairingError, serverPayloadDecodeError: FactoryServerPayloadDecodeError, correlation: FactoryCorrelation, protocolVersion: ProtocolVersion, protocolRange: ProtocolRange, manifest: ProtocolManifest, };
