// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryThreadStatus } from "./FactoryThreadStatus";
import type { ThreadId } from "./ThreadId";
import type { JsonValue } from "./serde_json/JsonValue";

export type FactoryThread = { id: ThreadId, sessionId: string, forkedFromId?: ThreadId, parentThreadId?: ThreadId, preview: string, ephemeral: boolean, modelProvider: string, createdAt: number, updatedAt: number, status: FactoryThreadStatus, cwd: string,
/**
 * Complete pinned app-server thread payload, including turns, items,
 * pagination-related fields, and fields not projected in Protocol V1.
 */
raw: JsonValue, };
