// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryChatgptAuthTokensRefreshReason } from "./FactoryChatgptAuthTokensRefreshReason";

export type FactoryChatgptAuthTokensRefreshParams = { reason: FactoryChatgptAuthTokensRefreshReason, previousAccountId: string | null, };
