// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable operation discriminator used to correlate a response with the
 * request that selected its result schema.
 */
export type FactoryMethod = "initialize" | "thread/start" | "thread/resume" | "thread/fork" | "thread/compact/start" | "turn/start" | "turn/steer" | "turn/interrupt";
