// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryUserInput } from "./FactoryUserInput";
import type { ItemId } from "./ItemId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Stable Factory projection of a Codex thread item.
 *
 * Every known projection carries the complete original payload in `raw`, so
 * consumers can use the stable fields without losing pinned upstream data.
 */
export type FactoryItem = { "type": "userMessage", id: ItemId, clientId?: string, content: Array<FactoryUserInput>, raw: JsonValue, } | { "type": "agentMessage", id: ItemId, text: string, phase?: string, memoryCitation?: JsonValue, raw: JsonValue, } | { "type": "plan", id: ItemId, text: string, raw: JsonValue, } | { "type": "reasoning", id: ItemId, summary: Array<string>, content: Array<string>, raw: JsonValue, } | { "type": "commandExecution", id: ItemId, command: string, cwd: string, processId?: string, status: string, aggregatedOutput?: string, exitCode?: number, durationMs?: number, raw: JsonValue, } | { "type": "fileChange", id: ItemId, changes: JsonValue, status: string, raw: JsonValue, } | { "type": "mcpToolCall", id: ItemId, server: string, tool: string, status: string, arguments: JsonValue, result?: JsonValue, error?: JsonValue, durationMs?: number, raw: JsonValue, } | { "type": "dynamicToolCall", id: ItemId, namespace?: string, tool: string, arguments: JsonValue, status: string, contentItems?: JsonValue, success?: boolean, durationMs?: number, raw: JsonValue, } | { "type": "collabAgentToolCall", id: ItemId, tool: string, status: string, senderThreadId: string, receiverThreadIds: Array<string>, prompt?: string, model?: string, reasoningEffort?: string, agentsStates: JsonValue, raw: JsonValue, } | { "type": "contextCompaction", id: ItemId, raw: JsonValue, } | { "type": "unknown", id?: ItemId, upstreamType: string, value: JsonValue, };
