// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryToolRequestUserInputQuestion } from "./FactoryToolRequestUserInputQuestion";
import type { ItemId } from "./ItemId";
import type { ThreadId } from "./ThreadId";
import type { TurnId } from "./TurnId";

export type FactoryToolRequestUserInputParams = { threadId: ThreadId, turnId: TurnId, itemId: ItemId, questions: Array<FactoryToolRequestUserInputQuestion>, autoResolutionMs: number | null, };
