// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryImageDetail } from "./FactoryImageDetail";

export type FactoryUserInput = { "type": "text", text: string, } | { "type": "image", url: string, detail?: FactoryImageDetail, } | { "type": "localImage", path: string, detail?: FactoryImageDetail, } | { "type": "audio", url: string, } | { "type": "localAudio", path: string, } | { "type": "skill", name: string, path: string, } | { "type": "mention", name: string, path: string, };
