// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryErrorEnvelope } from "./FactoryErrorEnvelope";
import type { FactoryNotificationEnvelope } from "./FactoryNotificationEnvelope";
import type { FactoryRequestEnvelope } from "./FactoryRequestEnvelope";
import type { FactoryResponseEnvelope } from "./FactoryResponseEnvelope";
import type { FactoryServerErrorResponse } from "./FactoryServerErrorResponse";
import type { FactoryServerResponse } from "./FactoryServerResponse";

/**
 * One JSON value per line. Deliberately follows app-server JSON-RPC
 * semantics without adding a `jsonrpc` member.
 */
export type FactoryJsonlMessage = FactoryRequestEnvelope | FactoryResponseEnvelope | FactoryErrorEnvelope | FactoryNotificationEnvelope | FactoryServerResponse | FactoryServerErrorResponse;
