// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryCommandExecutionApprovalDecision } from "./FactoryCommandExecutionApprovalDecision";

export type FactoryCommandExecutionRequestApprovalResponse = { decision: FactoryCommandExecutionApprovalDecision, };
