// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryRpcRequestId } from "./FactoryRpcRequestId";
import type { FactoryServerRequestMethod } from "./FactoryServerRequestMethod";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Exact raw app-server request shape. Keeping this beside a typed projection
 * prevents newly-added or deliberately unprojected params from being lost.
 */
export type FactoryRawServerRequest = { id: FactoryRpcRequestId, method: FactoryServerRequestMethod, params: JsonValue, };
