// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryRpcRequestId } from "./FactoryRpcRequestId";
import type { FactoryServerRequestMethod } from "./FactoryServerRequestMethod";

export type FactoryServerResponsePairingError = { "kind": "requestIdMismatch", expected: FactoryRpcRequestId, actual: FactoryRpcRequestId, } | { "kind": "methodMismatch", expected: FactoryServerRequestMethod, actual: FactoryServerRequestMethod, };
