// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryEvent } from "./FactoryEvent";

export type FactoryNotificationEnvelope = { "method": "initialized" } | { "method": "factory/event", "params": FactoryEvent };
