// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";
import type { TurnId } from "./TurnId";
import type { JsonValue } from "./serde_json/JsonValue";

export type FactoryRuntimeError = { message: string, codexErrorInfo?: JsonValue, additionalDetails?: string, willRetry: boolean, threadId: ThreadId, turnId: TurnId, };
