// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryNetworkPolicyRuleAction } from "./FactoryNetworkPolicyRuleAction";

export type FactoryNetworkPolicyAmendment = { host: string, action: FactoryNetworkPolicyRuleAction, };
