// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryClientInfo } from "./FactoryClientInfo";
import type { FactoryInitializeCapabilities } from "./FactoryInitializeCapabilities";

export type InitializeRequest = { clientInfo: FactoryClientInfo, capabilities?: FactoryInitializeCapabilities, };
