// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactoryThread } from "./FactoryThread";
import type { JsonValue } from "./serde_json/JsonValue";

export type ThreadResumeResponse = { thread: FactoryThread,
/**
 * Complete response payload, including initial turn pages and cursors.
 */
raw: JsonValue, };
