apiVersion: v1
kind: Namespace
metadata:
  name: __FACTORY_NAMESPACE__
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: __FACTORY_WORKSPACE_PV__
spec:
  capacity:
    storage: __FACTORY_WORKSPACE_SIZE_GIB__Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: factory-single-node
  local:
    path: __FACTORY_WORKSPACE_HOST_DIR__
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - __FACTORY_KUBERNETES_NODE_NAME__
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __FACTORY_WORKSPACE_PVC__
  namespace: __FACTORY_NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: factory-single-node
  volumeName: __FACTORY_WORKSPACE_PV__
  resources:
    requests:
      storage: __FACTORY_WORKSPACE_SIZE_GIB__Gi
